#pragma once
#include "carusos_config.h"

#if CARUSOS_LANG_ES
    #define TXT_BOOT_BOOTING "Arrancando CarusOS %s...\n"
    #define TXT_BOOT_PSRAM   "Montando PSRAM... (4MB)\n"
    #define TXT_BOOT_PANEL   "Inicializando Panel RGB...\n"
    #define TXT_BOOT_START   "Iniciando Escritorio...\n"
    #define TXT_APP_CALC_TITLE "Calculadora"
    #define TXT_APP_NTP_TITLE "Reloj NTP"
    #define TXT_APP_NTP_DESC  "Conectado a pool.ntp.org - OK"
    #define TXT_APP_AUDIO_TITLE "Estudio de Audio"
    #define TXT_APP_AUDIO_DESC  "Prueba de Hardware I2S (ES8311)"
    #define TXT_APP_INFO_TITLE "Configuracion"
    #define TXT_SYS_INFO_DESC "Version %s\nProcesador: ESP32-S3 Dual Core\n"
    #define TXT_BACK " Atras"
    #define TXT_SCREEN_SLEEP "Apagar"
    #define TXT_AUDIO_PLAY "Reproducir"
    #define TXT_AUDIO_STOP "Detener"
    #define TXT_AUDIO_VOL "Volumen"
    #define TXT_APP_SYSINFO_TITLE "Informacion del Sistema"
#else
    #define TXT_BOOT_BOOTING "Booting CarusOS %s...\n"
    #define TXT_BOOT_PSRAM   "Mounting PSRAM... (4MB)\n"
    #define TXT_BOOT_PANEL   "Initializing RGB Panel...\n"
    #define TXT_BOOT_START   "Starting Desktop...\n"
    #define TXT_APP_CALC_TITLE "Calculator"
    #define TXT_APP_NTP_TITLE "NTP Clock"
    #define TXT_APP_NTP_DESC  "Connected to pool.ntp.org - OK"
    #define TXT_APP_AUDIO_TITLE "Audio Studio"
    #define TXT_APP_AUDIO_DESC  "I2S Hardware Test (ES8311)"
    #define TXT_APP_INFO_TITLE "Settings"
    #define TXT_SYS_INFO_DESC "Version %s\nCPU: ESP32-S3 Dual Core\n"
    #define TXT_BACK " Back"
    #define TXT_SCREEN_SLEEP "Sleep"
    #define TXT_AUDIO_PLAY "Play"
    #define TXT_AUDIO_STOP "Stop"
    #define TXT_AUDIO_VOL "Volume"
    #define TXT_APP_SYSINFO_TITLE "System Information"
#endif
